# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish Platform Api'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/PlatformApi/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/webapp'
    zipAfterPublish: True
- task: DotNetCoreCLI@2
  displayName: 'Publish Azure Function'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/Functions/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/function'
    zipAfterPublish: True

- task: PublishPipelineArtifact@1
  displayName: 'Publish Platform Api Artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/webapp' 
    artifactName: 'air-bnb-webapp-artifact'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Azure Function Artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/function' 
    artifactName: 'air-bnb-function-artifact'