version: '3.8'

services:
    platformapi:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - '5001:80'
        depends_on:
            - sql
    sql:
        image: 'mcr.microsoft.com/mssql/server:2022-latest'
        container_name: sql_server2022
        ports: # not actually needed, because the two services are on the same network
            - '1433:1433'
        volumes:
            - ./sql-volume:/var/opt/mssql
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=MyPass@word
